services:
  openapi:
    image: openfusion-openapi-plugin
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: openfusion-openapi-plugin
    environment:
      DATABASE_PATH: ${DATABASE_PATH}
      ISSUER_NAME: ${ISSUER_NAME}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_SERVER_FROM_ACCOUNT_RELATED_EMAIL_ADDRESS: ${MAIL_SERVER_FROM_ACCOUNT_RELATED_EMAIL_ADDRESS}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
      MAIL_SERVER_USERNAME: ${MAIL_SERVER_USERNAME}
      VERIFICATION_TOKEN_SALT_KEY: ${VERIFICATION_TOKEN_SALT_KEY}
      VERIFICATION_TOKEN_SECURITY_KEY: ${VERIFICATION_TOKEN_SECURITY_KEY}
    ports:
      - 8080:8080
    volumes:
      - ${LOCAL_DATABASE_PATH}:${DATABASE_PATH}
