version: '3'

services:
  openapi:
    image: openfusion-openapi-plugin
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: openfusion-openapi-plugin
    environment:
      DATABASE_PATH: ${DATABASE_PATH}
      ISSUER_NAME: ${ISSUER_NAME}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
      MAIL_SERVER_USERNAME: ${MAIL_SERVER_USERNAME}
      SSL_KEY_ALIAS: ${SSL_KEY_ALIAS}
      SSL_KEY_STORE: ${SSL_KEY_STORE}
      SSL_KEY_STORE_PASSWORD: ${SSL_KEY_STORE_PASSWORD}
      SSL_KEY_STORE_TYPE: ${SSL_KEY_STORE_TYPE}
      VERIFICATION_TOKEN_SALT_KEY: ${VERIFICATION_TOKEN_SALT_KEY}
      VERIFICATION_TOKEN_SECURITY_KEY: ${VERIFICATION_TOKEN_SECURITY_KEY}
    ports:
      - 443:443
    volumes:
      - ${LOCAL_DATABASE_PATH}:${DATABASE_PATH}
      - ${LOCAL_SSL_KEY_STORE}:${SSL_KEY_STORE}:ro
