CREATE TABLE IF NOT EXISTS VerificationTokens (
    VerificationTokenID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Token TEXT NOT NULL UNIQUE,
    Type TEXT NOT NULL,
    AccountID INTEGER NOT NULL REFERENCES Accounts (AccountID) ON DELETE CASCADE,
    Created INTEGER DEFAULT (strftime('%s', 'now')) NOT NULL,
    Expires INTEGER NOT NULL,
    CHECK (Type IN ('EMAIL_VERIFICATION_TOKEN', 'RESET_PASSWORD_TOKEN'))
);
